baseURL = "https://cuetorials.com/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Cuetorials"
# theme = ""
pygmentsCodeFences = true
pygmentsStyle = "github"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

enableGitInfo = true

[params]
sitename="Cuetorials"
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = false # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
github_project_repo = "https://github.com/hofstadter-io/cuetorials.com"
github_repo = "https://github.com/hofstadter-io/cuetorials.com"
time_format_default = "January 2, 2006"
cuedocBase = "https://pkg.go.dev/cuelang.org/go@v0.4.0"
ga = "UA-103579574-6"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "v0.4.0 <i class='fas fa-copyright pl-2'></i> Cuelang.org"
url = "https://cuelang.org"
weight = 0

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub"
url = "https://github.com/cue-lang/cue"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-play-circle'></i> Playground"
url = "https://cuelang.org/play/"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-user'></i> Community"
url = "https://cuelang.org/community/"
weight = 3

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Cuetorials GH"
url = "https://github.com/hofstadter-io/cuetorials.com"
weight = 4
